export interface Tbcargasplanta {
    id?: bigint,
    idCarga?: bigint,
    estado?: string,
    codigo?: string,
    nombres?: string,
    primerApellido?: string,
    segundoApellido?: string,
    fechaInicioVigencia?: Date,
    email?: string,
    codigoEstablecimiento?: string,
    nombreEstablecimiento?: string,
    codigoUnidadTrabajo?: string,
    nombreUnidadTrabajo?: string,
    nivelExperto?: string,
    tipoTrabajador?: string,
    contrato?: string,
    descripcionContrato?: string,
    contratado?: string,
    realizaMarcaciones?: string,
    borrarInformacionFutura?: string,
    fechaRetiro?: Date,
    centroCostos?: string
}
